### ISSUE TITLE
yobit exchange wallet maintenance

### ISSUE THREAD

**Issue by abhayo1990** [Gulden/gulden-official#12]
is the possible to request maintenance from ur side of yobit wallet ?? at- https://yobit.net/en/maintenance_request/

**Comment by mjmacleod** [comment]
We already have multiple times. As I already stated, they do not reply.
I am very sorry that you are having problems with them but, they have nothing to do with us and really it is unreasonable for you to keep making it our problem.

1) This is our development issue tracker not a support system, there are plenty of proper support channels for you to go to.
2) There is absolutely nothing we can do, your problem is with Yobit not us.

My time is incredibly valuable and scarce, please do not continue to waste it by filling yobit bugs here.
Your problem is with Yobit - take it up with them.
