### ISSUE TITLE
Wallet HD index error

### ISSUE THREAD

**Issue by DutchRonin** [Gulden/gulden-official#125]
### Describe the issue
After upgrading from version 2005 to 2006 I get the following error when starting wallet:
'Wallet contains an HD index error, this is not immediately dangerous but should be rectified as soon as possible, please contact a developer for assistance.'

After clicking OK the wallet starts normally and seems to work normally.
Tried rescanning transactions without result.
Anything else I can try?

### What version of Gulden are you using?
Gulden version v2.0.0.6-57c4ebee5 (64-bit)

### Machine specs:
- OS: Win 10
- CPU: i7
- RAM: 32gb
- Disk size: 10TB
- Disk Type (HD/SDD): mixed

**Comment by mjmacleod** [comment]
1) This is a precautionary scan that has been added to the wallet to detect any users whose wallet has a problem that was caused by an issue we picked up and fixed already in a past build.
2) There is no immediate danger to funds or anything like that, but to prevent (a small chance) of confusion in future its best to deal with it sooner rather than later.

Steps to take:
1) Ensure you have recovery phrase; Close software and back up wallet.dat safely (keep a copy of this)
2) Remove wallet.dat
3) Restore from recovery phrase
4) Ensure all accounts and etc. are as expected - this will be the case in 99.99% of cases and if it is then nothing further to do - if not then seek further assistance.
5) If some balance is missing set a larger keypool `-keypool=100`, give wallet some time to generate keys and then rescan

Alternative easier steps (If not particularly attached to old wallet):
1) Empty wallet
2) Start a new clean wallet

**Comment by mjmacleod** [comment]
That would be nice yes :)

In the meantime sorry for the inconvenience

**Comment by DutchRonin** [comment]
Sure, no prob. You're all doing a great job.
