### ISSUE TITLE
Testing Gulden under mining pool

### ISSUE THREAD

**Issue by red0bear** [Gulden/gulden-official#134]
Hi there , i see your project with good potential but under pool mining gulden acts bad when running. well i know some issue here ... but lets go to errors. 

This seems more like private password from wallet [gulden] Could not dumpprivkey for gulden {"code":-32603,"message":"Please pass the correct HDConsent option in order to proceed."}

This happens many times when we are trying to mine blocks ....

[gulden] (Thread 4) getblocktemplate call failed for daemon instance 0 with error {"code":-32603,"message":"Failed to create new block, read GuldenD debug.log for more information"}

[gulden] (Thread 8) getblocktemplate call failed for daemon instance 0 with error {"code":-32603,"message":"Failed to create new block, read GuldenD debug.log for more information"}

[gulden] (Thread 5) getblocktemplate call failed for daemon instance 0 with error {"code":-32603,"message":"Failed to create new block, read GuldenD debug.log for more information"}

 getblocktemplate call failed for daemon instance 0 with error {"code":-32603,"message":"Failed to create new block, read GuldenD debug.log for more information"}

Well i wish your project have success but we need some fix or options to evade this problems.

**Comment by mjmacleod** [comment]
It seems the problem is with your expectations.

What you are expecting Gulden to be:
1) Yet another bitcoin clone that is just bitcoin with the name changed
2) That you can drop into some external software that was designed for bitcoin and everything will just work

Reality:
1) As one of the few currencies with lots of development Gulden is -drastically- different from bitcoin
2) If you want to mine Gulden you will need to understand these differences
3) You cannot just drop Gulden into some external software and call it a day but rather you will need to educate yourself on the differences between Gulden and other software - the HDConsent thing for instance would become immediately obvious to you simply by reading the RPC help - this is not something we can or will change on our side it is something you need to change on YOUR side.

Minimum reading: https://github.com/Gulden/gulden-official/blob/master/mining_documentation/mining_Gulden.md

For further support it is suggested you make use of our slack, as github issues are for actual issues and not for end user support.
