### ISSUE TITLE
Removed

### ISSUE THREAD

**Issue by Redsandro** [Gulden/gulden-official#14]
Removed.

**Comment by mjmacleod** [comment]
This site  has nothing to do with the dev team whatsoever.

**Comment by Redsandro** [comment]
I assumed it's was a pre-mine coin adoption project and/or set up by a dev or early adopter, and therefore it would make sense if someone here knew who's project this is/was.

"No idea" would suffice, but @rijkplasman is quick on censoring even the word from the title, so now I know that I've stepped into something dirty. :hankey:

**Comment by mjmacleod** [comment]
The reason it was removed is because we do not want to give free advertising to 'dodgy' projects that have nothing to do with us.

Now with respect, I am very very busy - I work incredibly long hours and I have a lot of important stuff to do, and you constantly insist on wasting my time here with issues that you yourself admit *DO NOT BELONG HERE* is not helpful to the project.

This issue tracker is here for a very specific reason - to track issues *WITH THE GULDEN SOURCE CODE*
There are many other places where you can go make political statements or ask about ways to acquire free coins or whatever it is that interests you.

So I'm going to be quite frank now, please stop putting issues that are not relevant on this issue tracker, and please keep the political BS off this issue tracker, show some respect to my time please. If you refuse to do this I will have no choice but to ban you from the tracker.
