### ISSUE TITLE
synchronizing hangs on block 797017

### ISSUE THREAD

**Issue by stresskiller** [Gulden/gulden-official#140]
upgraded yesterday to wallet 64 bits windows 2.0.0.15-63703b3a0

after 24 hrs still at 99% 

<edit: Removed inappropriate comments - github is for technical queries do not use it to try and stir trouble>

**Comment by mjmacleod** [comment]
Your chain is stuck in an invalid state due to failing to upgrade in time. In order to sync with the network again you will need to wipe your chainstate (or everything except wallet.dat if you want to keep it simple) and then restart with the updated client.

Note that this is really an end user query and does not belong here, for future queries of this nature make use of the proper support channels at support.gulden.com

**Comment by stresskiller** [comment]
just tried again to login to slack : 


Hi stresskiller,

You recently tried to sign in to Gulden, but it looks like your account for that workspace is deactivated. We're sorry about that!

If you think this was a mistake, please contact a Workspace Administrator to reactivate the account.

Cheers,
The team at Slack

**Comment by HarmJan1990** [comment]
You can always use the support chat on https://gulden.com/

**Comment by stresskiller** [comment]
for now the wallet is working again, i tried that chat in the past never got an answer back then.

**Comment by mjmacleod** [comment]
I'm glad the issue is resolved.

In order to avoid wasting developer time in future please refrain from creating excessive noise on the issue tracker:
1) This github is not a help desk there are multiple other avenues via which to seek help, two slacks an anonymous web support chat and various other avenues, so please use them. Abide by the rules and you will not have issues.
2) Write everything in a single message not multiple messages as this creates unnecessary noise
3) Refrain from talking about political views or other topics that are not directly to do with the software - I've had to edit multiple of your posts and this is not something that can go on.
