### ISSUE TITLE
Auto configure failure

### ISSUE THREAD

**Issue by tuaris** [Gulden/gulden-official#16]
Auto configure failure

```
libtoolize: putting auxiliary files in AC_CONFIG_AUX_DIR, 'build-aux'.
libtoolize: copying file 'build-aux/ltmain.sh'
libtoolize: putting macros in AC_CONFIG_MACRO_DIRS, 'build-aux/m4'.
libtoolize: copying file 'build-aux/m4/libtool.m4'
libtoolize: copying file 'build-aux/m4/ltoptions.m4'
libtoolize: copying file 'build-aux/m4/ltsugar.m4'
libtoolize: copying file 'build-aux/m4/ltversion.m4'
libtoolize: copying file 'build-aux/m4/lt~obsolete.m4'
configure.ac:45: installing 'build-aux/compile'
configure.ac:45: installing 'build-aux/config.guess'
configure.ac:45: installing 'build-aux/config.sub'
configure.ac:28: installing 'build-aux/install-sh'
configure.ac:28: installing 'build-aux/missing'
Makefile.am: installing 'build-aux/depcomp'
parallel-tests: installing 'build-aux/test-driver'
aclocal-1.15: warning: couldn't open directory 'build-aux/m4': No such file or directory
libtoolize: putting auxiliary files in AC_CONFIG_AUX_DIR, 'build-aux'.
libtoolize: copying file 'build-aux/ltmain.sh'
libtoolize: putting macros in AC_CONFIG_MACRO_DIRS, 'build-aux/m4'.
libtoolize: copying file 'build-aux/m4/libtool.m4'
libtoolize: copying file 'build-aux/m4/ltoptions.m4'
libtoolize: copying file 'build-aux/m4/ltsugar.m4'
libtoolize: copying file 'build-aux/m4/ltversion.m4'
libtoolize: copying file 'build-aux/m4/lt~obsolete.m4'
configure.ac:10: installing 'build-aux/compile'
configure.ac:5: installing 'build-aux/config.guess'
configure.ac:5: installing 'build-aux/config.sub'
configure.ac:9: installing 'build-aux/install-sh'
configure.ac:9: installing 'build-aux/missing'
Makefile.am:78: error: CPPFLAGS_FOR_BUILD must be set with '=' before using '+='
Makefile.am:79: error: CFLAGS_FOR_BUILD must be set with '=' before using '+='
Makefile.am: installing 'build-aux/depcomp'
parallel-tests: installing 'build-aux/test-driver'
autoreconf-2.69: automake failed with exit status: 1
*** Error code 1
```

**Comment by mjmacleod** [comment]
The problem is that your distro has ancient autotools on it.

See the README.md (https://github.com/Gulden/gulden-official/README.md) troubleshooting section  - which in turn will point you to the old_autotools branch - using this branch (which is identical codewise but makes allowances for old autotools) should resolve the issue..

**Comment by tuaris** [comment]
I'm revisiting those because it seems weird.  What version of autotools is it needing exactly because I have what appears to be the latest available:

```
autoconf-2.69_1                    =   up-to-date with index
autoconf-wrapper-20131203          =   up-to-date with index
automake-1.15.1                    =   up-to-date with index
automake-wrapper-20131203          =   up-to-date with index
```

**Comment by mjmacleod** [comment]
My initial assumption that this was related to the version of autotools appears to have been wrong.

It is related to some difference between autotools on different distros (or even different versions of the same distro) but I do not know what and have unfortunately larger priorities than trying to track down what it is, and don't have the depth of autotools expertise required to know what it is offhand. 
Just speculating but it is possibly a configuration of some kind.

Essentially in some cases/distros/machines it seems okay for Makefile.am to specify `CFLAGS_FOR_BUILD+=...` without first specifying `CFLAGS_FOR_BUILD=...` while on others this causes an error.

The obvious fix is to simply change the += to = but I'm not thrilled about this because it removes the ability for people to then pass in custom flags. There is probably a better way to fix this.

See related https://github.com/Gulden/gulden-official/issues/55 for further discussion.

**Comment by mjmacleod** [comment]
My initial assumption that this was related to the version of autotools appears to have been wrong.

It is related to some difference between autotools on different distros (or even different versions of the same distro) but I do not know what and have unfortunately larger priorities than trying to track down what it is, and don't have the depth of autotools expertise required to know what it is offhand. 
Just speculating but it is possibly a configuration of some kind.

Essentially in some cases/distros/machines it seems okay for Makefile.am to specify `CFLAGS_FOR_BUILD+=...` without first specifying `CFLAGS_FOR_BUILD=...` while on others this causes an error.

The obvious fix is to simply change the += to = but I'm not thrilled about this because it removes the ability for people to then pass in custom flags. There is probably a better way to fix this.

See related https://github.com/Gulden/gulden-official/issues/55 for further discussion.
