### ISSUE TITLE
Minor cosmetic improvements for 2.1.0.14

### ISSUE THREAD

**Issue by PanderMusubi** [Gulden/gulden-official#176]
Some minor improvements for the 2.1.0.14 gui, mainly the mining tab:
- 'Mb' should be 'MB'
- 'Kh' should be 'kh/s'
- six decimals for hashrate is a bit too much, three would be enough
- icon for mobile on the left should be horizontally centered with other icons such as diamond for mining, credit card for my account and symbol for witness account

**Comment by mjmacleod** [comment]
I've addressed all the items except the icons, though it doesn't look it at first glance the icons are actually all equally aligned.
Attached a zoomed in screenshot demonstrating this.

If you have a machine on which you think this is not the case please attach a screenshot and more details, otherwise I consider this closed.

![Screenshot_20191021_152138](https://user-images.githubusercontent.com/7540840/67208812-7facce00-f416-11e9-8db4-c23f06b49b5a.png)
