### ISSUE TITLE
Gulden is always up to date

### ISSUE THREAD

**Issue by timkoers** [Gulden/gulden-official#234]
### Describe the issue

When checking for an update via the Help -> Check for updates button, the client always says that there is no newer version available.

#### If so, please list the steps to reproduce below:
1. Open Gulden v2.3.0.6 x64 
2. Start mining gulden
3. Check for updates using Help -> Check for updates.

### Expected behaviour
An message should appear that states that version v2.3.8 is available.

### Actual behaviour
The message that no update is available appears.

### What version of Gulden are you using?
Gulden v2.3.0.6 x64 

### Machine specs:
- OS: Windows 10 x64 20H2
- CPU: Ryzen 9 3900X
- RAM: 32GB
- Disk size: 512GB
- Disk Type (HD/SDD): SSD

**Comment by achterhooker** [comment]
Some updates are minor enhancements/bugfixes, others are important or even mandatory updates. At this very moment it is mostly fine if you are at v2.2.0.14 or above. The "check for updates" is manually set by the devs and at v2.3.0.6 you are perfectly fine. Only important updates get flagged so that your wallet tells you there is an update.

**Comment by mjmacleod** [comment]
As per description above, we don't always use the auto update for minor point releases, you will notice it has been used for the latest 2.4.0 release.

We will consider using it more in future.
