### ISSUE TITLE
Dumpprivkey function error

### ISSUE THREAD

**Issue by wonseok4840** [Gulden/gulden-official#69]
when I run ./Gulden-cli dumpprivkey [MyAddress], it shows this:
"Please pass the correct HDConsent option in order to proceed."
What can I do to solve this?

**Comment by mjmacleod** [comment]
"help privkey"

dumpprivkey "address"

Reveals the private key corresponding to 'address'.
Then the importprivkey can be used with this output
WARNING! If a dumped private key from an HD account is exposed or given out -all- keys within that account (current and future) are also at risk, if the attacker can also get hold of your public key for that account.

Arguments:
1. "address"   (string, required) The Gulden address for the private key
2. "HDConsent"        (string, optional) If dumping from an HD account please pass the string 'I_UNDERSTAND_AND_ACCEPT_THE_RISK_OF_DUMPING_AN_HD_PRIVKEY' for this paramater, if you do not understand the risk then please do not do this.

Result:
"key"                (string) The private key

Examples:
> Gulden-cli dumpprivkey "myaddress"
> Gulden-cli importprivkey "mykey"
> curl --user myusername --data-binary '{"jsonrpc": "1.0", "id":"curltest", "method": "dumpprivkey", "params": ["myaddress"] }' -H 'content-type: text/plain;' http://127.0.0.1:8332/

**Comment by wonseok4840** [comment]
So, you said that the "HDConsent" argument is optional. However, it seems to me that it is not. When I don't type that argument, it shows that error message that I got before. Is this right, or am I understanding it wrong?

**Comment by mjmacleod** [comment]
When dumping from an HD account it is -required- to pass this option in order to acknowledge that you have read the help and  understand what you are doing. When dumping from a non-HD account it is not required and therefore optional.

If you don't understand why you should not be dumping the key from an HD account you probably shouldn't be doing so to begin with.

Note that this github is for reports of bugs only and not for end user support, in future for end user support please use official support channels https://gulden.com/support and not this github.
