### ISSUE TITLE
Gulden wallet windows  issue

### ISSUE THREAD

**Issue by Shilpheed** [Gulden/gulden-official#70]
Issue with the recieve adres changing  after restart wallet  and unable to add new recieve adresses , only accounts.

I am having a issue on windows 10 where the windows wallet wil not generate any new adressen through adressen ontvangen.  You can add the name tag but hitting ok does not do anything other light up the button shortly.
question mark help function in those windows also do not repond.

Ive had this and i was not aware of another issue that my  standard wallet recieve adres also has changed.  so the miners i set on my initial adress profit is also lost at this point.

I asume this is not by design but i would like to know what is wrong or if this is just an issue im having running gulden wallet Gulden versie v1.6.4.6-cd0b48c (64-bit)   on windows 10 Version 10.0.15063

**Comment by mjmacleod** [comment]
Generation of new wallet addresses is standard wallet behaviour that is both intentional and desirable, all old addresses still also remain available in the wallet.

This github is for technical users, for end user support please visit https://gulden.com/support.
Please do not file bugs without first verifying with support that there is an actual issue.
